plugins {
    id 'java'
}

group = 'cn.simpfun'
version = '2.6.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files('libs/Mindustry.jar')
    compileOnly files('libs/server-release.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

jar {
    archiveFileName = 'MapMenu.jar'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
}
